task: cifar10
seed: 0
batch_size: 120
algorithms: [adam, pbm, alm_proj, alm_max, ssg]

constraint:
  name: LossPairwise
  bound: 0.1
  loss: CrossEntropyLoss

hydra:
  run:
    dir: .
  job:
    chdir: false