task: equalized_odds_pairwise

# seed: 0

batch_size: 72

# TODO: rework to list (constraints: [(name: ...), (name: ...), ...])
constraint:
  name: FairretPairwise
  bound: 0.1
  statistic: PositiveRate
  kwargs:
    uses_labels: false

# hydra:
#   run:
#     dir: .
#   job:
#     chdir: false
