task: equalized_odds_pairwise
seed: 0
batch_size: 72
algorithms: [adam, pbm, alm_proj, alm_max, ssg]

constraint:
  name: FairretPairwise
  bound: 0.1
  statistic: PositiveRate
  kwargs:
    uses_labels: false

hydra:
  run:
    dir: .
  job:
    chdir: false