task: equalized_odds_pairwise
batch_size: 30

# TODO: rework to list (constraints: [(name: ...), (name: ...), ...])
constraint:
  name: FairretPairwise
  bound: 0.1
  statistic: PositiveRate
  kwargs:
    uses_labels: false

hydra:
  run:
    dir: .
  job:
    chdir: false
