name: pbm_logscaled
updater: primal_dual
constraints_to_eq: false
select_filter: upper
primal:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
moreau:
  mu: 1.0
dual:
  _target_: humancompatible.train.dual_optim.PBM
  _partial_: true
  penalty_mult: 0.1
  penalty_annealing: true
  penalty_update: dimin_adapt
  pbf: quadratic_logarithmic
  gamma: null
  delta: 1.0
  penalty_range: [0.1, 1.0]
  gamma_annealing: null
  primal_update_process_length: 1
  logscaled_dual_update: true
  logscaled_dual_step_size: 1.0
