hydra:
  run:
    dir: multirun/${task.task}_${data.name}/${algorithm.algorithm}
  sweep:
    dir: multirun/${task.task}_${data.name}
    subdir: ./${algorithm.algorithm}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 60
    cpus_per_task: 4
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: null
    nodes: 1
    name: ${hydra.job.name}
    stderr_to_stdout: false
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: h200fast,amdgpufast
    qos: null
    comment: null
    constraint: null
    exclude: null
    gres: gpu=1
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: 16G
    account: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: 100
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - algorithm=alm_slack
    - algorithm.primal__lr=0.0001,0.0005,0.001,0.005
    - +algorithm.primal__weight_decay=0.01
    - algorithm.dual__lr=0.0001,0.0005,0.001,0.005
    - algorithm.dual__penalty=0.,1.,2.
    - algorithm.moreau__mu=1.
    - seed=0,1,2
    - task=cifar10_loss
    - data=dutch
  job:
    name: run_single_experiment
    chdir: false
    override_dirname: +algorithm.primal__weight_decay=0.01,algorithm.dual__lr=0.0001,0.0005,0.001,0.005,algorithm.dual__penalty=0.,1.,2.,algorithm.moreau__mu=1.,algorithm.primal__lr=0.0001,0.0005,0.001,0.005,algorithm=alm_slack,data=dutch,seed=0,1,2,task=cifar10_loss
    id: ???
    num: ???
    config_name: experiment
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /mnt/personal/kliacand/humancompatible-train/benchmark
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /mnt/personal/kliacand/humancompatible-train/benchmark/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      algorithm: alm_slack
      data: dutch
      task: cifar10_loss
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: configured_submitit_slurm_amdgpu
      hydra/output: default
  verbose: false
task:
  task: cifar10
  batch_size: 120
  constraint:
    name: LossPairwise
    bound: 0.1
    loss: CrossEntropyLoss
data:
  name: dutch
  kwargs:
    sens_attrs:
    - AGE
    - SEX
    extend_groups: false
algorithm:
  algorithm: alm_slack
  primal__lr: 0.0001, 0.0005, 0.001, 0.005
  dual__lr: 0.0001, 0.0005, 0.001, 0.005
  dual__penalty: 0., 1., 2.
  moreau__mu: 1.0
  primal__weight_decay: 0.01
n_epochs: 10
seed: 0
