,algorithm,primal__lr,dual_penalty_mult,dual__penalty_update,dual__pbf,dual__gamma,dual__delta,moreau__mu
1939d0d0,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
f596628e,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
f5e2b60e,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
3963b135,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
c0d8d373,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
8e25289f,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
1f0efedc,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
2ee5643c,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
09966201,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
8f0015d4,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
502d63b6,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
7706dd50,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
b8744781,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
0bd76ed9,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
cfc1a1a0,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
4ca90b82,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
ef8fd315,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
765765fc,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
e12e0f81,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
7657d8d8,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
3cbd2ee6,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
22f07a4c,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
e92df81c,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
b22ff058,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
8052c7ac,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
9a6f1866,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
d1013bcf,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
c5e16fb3,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
1408cbf8,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
a7e90ddd,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
76a4304b,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
6f0c87d0,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
5e6a09e5,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
07493314,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
91b33a17,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
7099b4f4,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
0a3bac31,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
0bf36ff7,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
9901c26f,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
931e4299,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
4f62168a,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
55ffba5f,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
38b46727,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
a7b65e32,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
a0b14bd1,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
86c8e8f3,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
f7d3a60c,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
f8c9637d,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
efc32755,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
aacd8398,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
964cc284,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
dca6fdde,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
5223edf2,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
1a61dc34,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
4f89a248,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
e393cbed,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
ecef3a00,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
0e0da02a,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
23a57e34,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
52bba476,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
451e31d0,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
b3e89f73,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
1e1cc2eb,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
b2138db2,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
b02ac3ef,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
667a7f50,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
712532d6,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
7eb9227e,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
c749cef2,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
c22b6836,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
a4e5877a,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
39c627b6,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
cae4df7d,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
42a77620,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
8d5a0c54,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
389ca72b,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
90e46eea,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
a72a36c5,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
4515b686,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
5298ab47,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
e9127df8,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
1b7b433b,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
c22458d5,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
e8322e81,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
891879e7,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
d62fb127,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
617a1969,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
b7857a23,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
1afb9541,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
cdd1e561,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
da47f1dd,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
ba274a55,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
0e5dc653,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
ee2c9b1a,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
9c9029d6,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
3583e68b,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
e78ef8d4,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
716133f0,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
06b31eb2,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
897ca06c,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
18f9cee1,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
da1b3c6a,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
2899f933,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
cc7b70a5,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
d0e29c58,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
c4fcd59f,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
62639632,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
c52f053c,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
a9f6a045,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
584f64b0,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
a8da0682,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
5f27203d,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
6a4334d2,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
cfeaeb53,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
6f1a514c,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
53cdf3a2,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
1fb5ad24,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
28406004,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
ec1b5d6d,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
bf93244f,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
6db3a1d5,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
ba5256a5,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
fc3e315b,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
b8e1fbec,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
b6109144,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
ab16aa38,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
b69a3f0d,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
9d9186ea,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
f78c23cb,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
4244be22,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
a9c3121d,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
1e327c5b,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
96c010df,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
ba4453c2,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
980303e8,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
8d20dc9d,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
7b9a9149,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
941dfa2d,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
b9f529cd,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
bff1c9aa,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
ff9a8046,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
ba1a19fe,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
ece78b87,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
e3b1577b,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
b891d7e9,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
99b2620b,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
7ca1bb04,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
3afec6bb,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
500d2b1b,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
81cde4b1,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
6689d9d9,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
b8ee3ce3,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
3eaaa559,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
9ec720d3,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
120de484,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
3000d330,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
cb0f7d98,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
a8d08839,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
d073a2fe,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
ac5546d1,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
7e3dc393,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
e4df822b,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
afe8f39f,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
6c0e111d,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
a36b06bb,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
61babd7a,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
9498932e,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
9e6c964e,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
15999499,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
ed753c3d,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
d1038859,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
18b259a8,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
2c79a3e5,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
00911656,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
8698af07,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
cecee675,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
92425387,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,0
be6e04cc,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
c2d8119a,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
242c0791,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
5df67a35,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
1eb8a2ed,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
1582f44b,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
c3496ba1,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
fba02db1,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,1.0
4fb6eacb,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
b119f84a,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
61e03d7e,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
da7c507a,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
4f64a795,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
360b8b34,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
39677ecb,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
30b307b1,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
38c72a41,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,1.0
13e4a4fa,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
bbd5d752,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
81e5e893,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
1ed62dd1,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
298e7286,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
fde99065,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.5
85794c11,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
5decd08b,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
c8b07e1d,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
b4f009ad,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
f8673eaa,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
a149258e,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
d6577c38,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
262f58fa,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
b1b47cb0,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
f52016ad,pbm_adapt,0.0001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,0
9839e7fc,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
22b98980,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
8f8e8714,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
e9ef7f84,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
fc79e06d,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
8b3ded22,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
7f4ca63a,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
93e274d5,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0
45ede71b,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.5
9b8432b3,pbm_adapt,0.005,0.9,dimin_adapt,quadratic_logarithmic,0.999,1.0,0
63fdd427,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,2.0
412b5708,pbm_adapt,0.005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
c782df54,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,0.1
9781862e,pbm_adapt,0.0005,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
0b391f37,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,0.1
566c01fa,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
407f2cd4,pbm_adapt,0.001,0.9,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
83d90b35,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
a599ba73,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
477bc467,pbm_adapt,0.0005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,1.0
f41c72f6,pbm_adapt,0.0005,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
9e4f73ee,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.5
483bbbbc,pbm_adapt,0.005,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.5
13a65243,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
fc795759,pbm_adapt,0.001,0.99,dimin_adapt,quadratic_logarithmic,0.9,1.0,0.1
edbfa24f,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.999,1.0,2.0
9d7d041f,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.5,1.0,0.1
b9d80d09,pbm_adapt,0.001,0.999,dimin_adapt,quadratic_logarithmic,0.9,1.0,1.0
4a072978,pbm_adapt,0.0001,0.99,dimin_adapt,quadratic_logarithmic,0.99,1.0,2.0
5cf9d8e3,pbm_adapt,0.0001,0.999,dimin_adapt,quadratic_logarithmic,0.5,1.0,2.0
